Repository suryanshsingh2001/MyLibrary, pull requests merged in 2024-10, with the labels that each got.

#54 Search Loading Icon #48
  client/src/Components/Search.jsx
Labels: bug, hacktoberfest-accepted, ui

#60 add infinite scroll
  client/src/Components/BookList.jsx
Labels: enhancement, hacktoberfest-accepted

#64 add infinite scroll
  client/src/Components/BookList.jsx
Labels: hacktoberfest-accepted

#69 Update README.md (#25)
  README.md
Labels: hacktoberfest-accepted, nocode

#76 Revert "i18n "
  client/package-lock.json
  client/package.json
  client/public/i18n/en-us.json
  client/public/i18n/it-it.json
  client/src/Components/BookList.jsx
  client/src/Components/Cart.jsx
  client/src/Components/Footer.jsx
  client/src/Components/Form/Dropdown.jsx
  client/src/Components/Header.jsx
  client/src/Components/Loading.jsx
  client/src/Components/Search.jsx
  client/src/Components/index.js
  client/src/main.jsx
  client/src/utils/i18n.js
  client/src/utils/index.js
Labels: bug, hacktoberfest-accepted

#75 Fixed pagination bug
  client/package-lock.json
  client/src/Components/BookList.jsx
Labels: hacktoberfest-accepted, rebase
